FROM debian
RUN apt update && apt upgrade -y
RUN apt install wget -y
RUN cd /tmp
RUN wget https://bitcoincore.org/bin/bitcoin-core-26.0/bitcoin-26.0-x86_64-linux-gnu.tar.gz 
RUN tar -xvf bitcoin-26.0-x86_64-linux-gnu.tar.gz 
RUN install -m 0755 -o root -g root -t /usr/local/bin bitcoin-26.0/bin/*
RUN mkdir /root/.bitcoin && cd /root/.bitcoin
ENTRYPOINT ["bitcoind"]
