FROM debian
RUN apt update && apt -y upgrade
RUN apt install -y cargo clang cmake build-essential git 
RUN mkdir rust && cd rust && git clone --branch v"0.10.4"  https://github.com/romanz/electrs.git
RUN cd rust/electrs && cargo build --locked --release
RUN install -m 0755 -o root -g root -t /usr/local/bin rust/electrs/target/release/electrs
RUN mkdir /root/.electrs
WORKDIR /root/.electrs
CMD ["electrs","--conf","electrs.conf"]
