FROM debian
RUN apt update && apt -y upgrade
RUN apt install -y wget && apt install -y gpg && apt install -y apt-transport-https
COPY tor.list /etc/apt/sources.list.d/
RUN wget -qO- https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --dearmor | tee /usr/share/keyrings/tor-archive-keyring.gpg >/dev/null
RUN apt update && apt -y upgrade
RUN apt install -y tor deb.torproject.org-keyring
ENTRYPOINT ["tor"]
